# Generated by Django 5.1 on 2024-08-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_postings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
